import = ["/home/dns/.config/alacritty/dracula.toml"]

live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = false

[cursor]
style = "Beam"
unfocused_hollow = true
vi_mode_style = "Block"

[font]
builtin_box_drawing = true
size = 8

[font.bold]
family = "Nerd Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
chars = "\u001B[72;5u"
key = "H"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[74;5u"
key = "J"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[75;5u"
key = "K"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[76;5u"
key = "L"
mods = "Control|Shift"

[mouse]
hide_when_typing = true

[scrolling]
history = 3000
multiplier = 3

[selection]
save_to_clipboard = true

[shell]
program = "/bin/zsh"

[window]
opacity = 0.75
